sudo: required
dist: xenial

script:
  - bundle exec rake test_app
  - bundle exec rake spec


language: ruby
cache: bundler
addons:
  chrome: stable

rvm:
  - 2.6
gemfile:
  - gemfiles/spree_3_6.gemfile
  - gemfiles/spree_3_7.gemfile
  - gemfiles/spree_4_0.gemfile
  - gemfiles/spree_4_1.gemfile
  - gemfiles/spree_master.gemfile