sudo: required
dist: trusty

script:
  - bundle exec rake test_app
  - bundle exec rake spec

env:
  - DB=mysql
  - DB=postgres

language: ruby
cache: bundler

rvm:
  - 2.6.0

before_install:
  - mysql -u root -e "GRANT ALL ON *.* TO 'travis'@'%';"
